### ISSUE TITLE
'No Such device' errror aufter executing 'sudo insmod qc71_laptop.ko' on Arch

### ISSUE THREAD

**Issue by steveroch-rs** [pobrn/qc71_laptop#1]
Following the installation guide exactly and trying both manual and DKMS installation, the insmod/modprobe commands return following error:

insmod: ERROR: could not insert module qc71_laptop.ko: No such device

**Comment by pobrn** [comment]
Please provide the output of `dmesg` (the relevant messages are prefixed by "qc71_laptop") when you try to load the module. Attach the content of `cat /sys/class/dmi/id/modalias` and the output of `ls -l /sys/bus/wmi/devices/`.

**Comment by steveroch-rs** [comment]
`> dmesg`
`[15093.495552] qc71_laptop: 'LAPQC71X' found`
`[15093.495555] qc71_laptop: could not install WMI notify handler: [21] AE_ALREADY_ACQUIRED`

DMI:
`dmi:bvnIntelCorp.:bvrQCCFL357.0116.2020.0619.1354:bd06/19/2020:svnSchenkerTechnologiesGmbH:pnXMGFUSION15(XFU15L19):pvrLate2019:rvnIntelCorporation:rnLAPQC71A:rvrK54899-303:cvnSchenkerTechnologiesGmbH:ct10:cvr1.0:`

WMI devices:

- lrwxrwxrwx 1 root root 0 Aug  8 10:32 05901221-D566-11D1-B2F0-00A0C9062910 -> ../../../devices/platform/PNP0C14:03- /wmi_bus/wmi_bus-PNP0C14:03/05901221-D566-11D1-B2F0-00A0C9062910
- lrwxrwxrwx 1 root root 0 Aug  8 10:32 86CCFD48-205E-4A77-9C48-2021CBEDE341 -> ../../../devices/platform/PNP0C14:02/wmi_bus/wmi_bus-PNP0C14:02/86CCFD48-205E-4A77-9C48-2021CBEDE341
- lrwxrwxrwx 1 root root 0 Aug  8 10:32 8C5DA44C-CDC3-46B3-8619-4E26D34390B7 -> ../../../devices/platform/PNP0C14:05/wmi_bus/wmi_bus-PNP0C14:05/8C5DA44C-CDC3-46B3-8619-4E26D34390B7
- lrwxrwxrwx 1 root root 0 Aug  8 10:32 A486D8F8-0BDA-471B-A72B-6042A6B5BEE0 -> ../../../devices/pci0000:00/PNP0C14:00/wmi_bus/wmi_bus-PNP0C14:00/A486D8F8-0BDA-471B-A72B-6042A6B5BEE0
- lrwxrwxrwx 1 root root 0 Aug  8 10:32 ABBC0F6A-8EA1-11D1-00A0-C90629100000 -> ../../../devices/platform/PNP0C14:04/wmi_bus/wmi_bus-PNP0C14:04/ABBC0F6A-8EA1-11D1-00A0-C90629100000
- lrwxrwxrwx 1 root root 0 Aug  8 10:32 ABBC0F6B-8EA1-11D1-00A0-C90629100000 -> ../../../devices/platform/PNP0C14:04/wmi_bus/wmi_bus-PNP0C14:04/ABBC0F6B-8EA1-11D1-00A0-C90629100000
- lrwxrwxrwx 1 root root 0 Aug  8 10:32 ABBC0F6C-8EA1-11D1-00A0-C90629100000 -> ../../../devices/platform/PNP0C14:04/wmi_bus/wmi_bus-PNP0C14:04/ABBC0F6C-8EA1-11D1-00A0-C90629100000
- lrwxrwxrwx 1 root root 0 Aug  8 10:32 ABBC0F6D-8EA1-11D1-00A0-C90629100000 -> ../../../devices/platform/PNP0C14:04/wmi_bus/wmi_bus-PNP0C14:04/ABBC0F6D-8EA1-11D1-00A0-C90629100000
- lrwxrwxrwx 1 root root 0 Aug  8 10:32 ABBC0F6E-8EA1-11D1-00A0-C90629100000 -> ../../../devices/platform/PNP0C14:04/wmi_bus/wmi_bus-PNP0C14:04/ABBC0F6E-8EA1-11D1-00A0-C90629100000
- lrwxrwxrwx 1 root root 0 Aug  8 10:32 ABBC0F6F-8EA1-11D1-00A0-C90629100000 -> ../../../devices/platform/PNP0C14:04/wmi_bus/wmi_bus-PNP0C14:04/ABBC0F6F-8EA1-11D1-00A0-C90629100000
- lrwxrwxrwx 1 root root 0 Aug  8 10:32 ABBC0F70-8EA1-11D1-00A0-C90629100000 -> ../../../devices/platform/PNP0C14:04/wmi_bus/wmi_bus-PNP0C14:04/ABBC0F70-8EA1-11D1-00A0-C90629100000
- lrwxrwxrwx 1 root root 0 Aug  8 10:32 ABBC0F71-8EA1-11D1-00A0-C90629100000 -> ../../../devices/platform/PNP0C14:04/wmi_bus/wmi_bus-PNP0C14:04/ABBC0F71-8EA1-11D1-00A0-C90629100000
- lrwxrwxrwx 1 root root 0 Aug  8 10:32 ABBC0F72-8EA1-11D1-00A0-C90629100000 -> ../../../devices/platform/PNP0C14:04/wmi_bus/wmi_bus-PNP0C14:04/ABBC0F72-8EA1-11D1-00A0-C90629100000
- lrwxrwxrwx 1 root root 0 Aug  8 10:32 CA4982BF-C230-458E-B12F-6F16475F351B -> ../../../devices/pci0000:00/PNP0C14:00/wmi_bus/wmi_bus-PNP0C14:00/CA4982BF-C230-458E-B12F-6F16475F351B
- lrwxrwxrwx 1 root root 0 Aug  8 10:32 DBBC0F6F-8EA1-11D1-00A0-C90629100000 -> ../../../devices/platform/PNP0C14:03/wmi_bus/wmi_bus-PNP0C14:03/DBBC0F6F-8EA1-11D1-00A0-C90629100000
- lrwxrwxrwx 1 root root 0 Aug  8 10:32 F6CB5C3C-9CAE-4EBD-B577-931EA32A2CC0 -> ../../../devices/pci0000:00/PNP0C14:01/wmi_bus/wmi_bus-PNP0C14:01/F6CB5C3C-9CAE-4EBD-B577-931EA32A2CC0

**Comment by pobrn** [comment]
Do you have the [`xmg_fusion_15`](https://github.com/pobrn/xmg_fusion_15) kernel module installed? If so, please remove it by running `sudo ./scripts/dkms_uninstall.sh`.

**Comment by steveroch-rs** [comment]
I do not.
However I was previously running `aucc` before discovering your tool (ite8291r3-ctl) through reddit. I removed aucc before however.

**Comment by pobrn** [comment]
Do you have tuxedo control center or anything that might interfere?

**Comment by steveroch-rs** [comment]
Yes I do have TCC installed. So I have to decide between controlling the lightbar and using TCC?

**Comment by pobrn** [comment]
Possibly yes. The operation of TCC may interfere with this kernel module since both communicate with the embedded control, which may lead to undesired effects.

**Comment by steveroch-rs** [comment]
Then I'll just leave it as is. I am very very happy with your other tool for the keyboard's RGB. Looking forward to further development.

**Comment by pobrn** [comment]
If you don't mind me asking, do the keyboard brightness function keys and the performance mode button work? And how much functionality does TCC provide (I've never used it that's why I'm asking)?
