### ISSUE TITLE
Is possible to make a separatable battery module?

### ISSUE THREAD

**Issue by right-0903** [pobrn/qc71_laptop#15]
I do some changes(I think dmi check has an impact on the compatibility of most of tongfan chassis), then I succeed in enabling battery feature for KC57/NUC X15/XMG FUSION 15 m22. Out of convinience, I use tcc, but qc71 module has some conflicts with tcc. I am struggling for a separatable battery module. But I chose C as one of my elective course many years ago, I know about C less. I am puzzled about where is the definition of the function `ec_read_bytes` and `ec_write_bytes`.

**Comment by pobrn** [comment]
You mean `ec_{read,write}_byte`? Those are defined in `ec.h`

**Comment by right-0903** [comment]
Thanks for your work. I work it out. I make some rough changes . And I still keep `battery.c` `battery.h` `ec.c` `ec.h` `wmi.h` to minimize my workload.
