### ISSUE TITLE
ERROR: could not insert module qc71_laptop.ko: No such device

### ISSUE THREAD

**Issue by lucasjome** [pobrn/qc71_laptop#2]
![image](https://user-images.githubusercontent.com/15149319/97051961-88b70a80-1556-11eb-8bbf-4190f86e5432.png)

log:
dmesg show: qc71_laptop: no DMI match

info:
OS: Arch Linux - 5.9.1 Kernel
Bios version: 0122

**Comment by pobrn** [comment]
Please post the output of `cat /sys/devices/virtual/dmi/id/modalias`.

**Comment by lucasjome** [comment]
dmi:bvnIntelCorp.:bvrQCCFL357.0122.2020.0911.1520:bd09/11/2020:br5.13:efr1.25:svnAvellHighPerformance:pnA60MUV:pvr:rvnAvellHighPerformance:rnAvellHighPerformance:rvr:cvnAvellHighPerformance:ct10:cvr1.0:

**Comment by pobrn** [comment]
The reason why the DMI board name has been changed to "AvellHighPerformance" will elude me for ever... Nonetheless, please pull from the `master` and try again.

**Comment by lucasjome** [comment]
It was showing same error on dmesg, so i did a PR for you. I already tested here and it worked. Thank you.
