### ISSUE TITLE
"Error 2" when compiling the module via "make" command

### ISSUE THREAD

**Issue by mtg92** [pobrn/qc71_laptop#4]
I was able to install the linux headers and dkms but when it comes time to compile the module via the "sudo make" command, I get the error below. Any idea how I could fix it? Thanks.

![qc71_laptop_make_error](https://user-images.githubusercontent.com/64047750/97780906-87519780-1b7f-11eb-8c25-a17ccb6003e9.png)

**Comment by pobrn** [comment]
You shouldn't use `sudo make`, just simply `make`.

**Comment by mtg92** [comment]
> You shouldn't use `sudo make`, just simply `make`.

Thanks for the quick reply. I've run 'make' and now the error is slightly different.

![qc71_laptop_make_error2](https://user-images.githubusercontent.com/64047750/97781794-a7845500-1b85-11eb-8444-c944b19baf3f.png)

Is this related to the linux-headers? Apologies for the 'noobness'!

**Comment by pobrn** [comment]
First please try purging, then reinstalling the linux-headers package.

**Comment by mtg92** [comment]
> First please try purging, then reinstalling the linux-headers package.

Thanks a lot, reinstalling the linux-headers package did the trick. I'll close this now :)

One other issue I'm seeing is that trying to change the lightbar parameters returns a "Permissions Denied" message, even if run with sudo. 

mtg92@pop-os:~/qc71_laptop$ echo 1 > /sys/class/leds/qc71_laptop::lightbar/brightness
bash: /sys/class/leds/qc71_laptop::lightbar/brightness: Permission denied
mtg92@pop-os:~/qc71_laptop$ sudo !!
sudo echo 1 > /sys/class/leds/qc71_laptop::lightbar/brightness
bash: /sys/class/leds/qc71_laptop::lightbar/brightness: Permission denied

**Comment by pobrn** [comment]
The reason for that is that only the `echo` is run as `root`. The redirection (`>`) is done by the shell, which run as your user, and the file is not writable by any ordinary account, thus you get the permission denied error. You can do this instead:
```
$ echo 1 | sudo tee /sys/class/leds/qc71_laptop::lightbar/brightness
```
