### ISSUE TITLE
[Feature Request] Set Fan Speed

### ISSUE THREAD

**Issue by lucasjome** [pobrn/qc71_laptop#5]
Would be possible to set fan speed, similar to how the control center works on Windows?

**Comment by pobrn** [comment]
It is possible to do so, if you want to try it. First you need to run `echo 1 | sudo tee /sys/devices/platform/qc71_laptop/manual_control`, after that you'll be able to control the fans using any standard fan control utility (like `fancontrol`). Or manually:
```
echo 1 | sudo tee /sys/devices/platform/qc71_laptop/hwmon/hwmon*/pwm1_enable # switch to manual fan control
echo 150 | sudo tee /sys/devices/platform/qc71_laptop/hwmon/hwmon*/pwm1 # set PWM betwenn 0 and 255
```

Note, that this has some limitations: keyboard backlight hotkeys and performance mode switching won't work at the moment. You can turn off "manual control" by running `echo 0 | sudo tee /sys/devices/platform/qc71_laptop/manual_control`, which will switch to automatic fan control, and where keyboard backlight hotkeys and performance mode switching works.

**Comment by lucasjome** [comment]
Thank you, will try for sure.

Just checking here my current values and i saw that `/sys/devices/platform/qc71_laptop/hwmon/hwmon*/pwm1_enable` is set to `2`. What are the possible values of this property?

**Comment by pobrn** [comment]
| value |  meaning   |
|-------|------------|
|  `2`  | automatic  |
|  `1`  |   manual   |
|  `0`  | full speed |
