### ISSUE TITLE
sudo insmod qc71_laptop.ko insmod: ERROR: could not insert module qc71_laptop.ko: File exists

### ISSUE THREAD

**Issue by CuriousxOctopus** [pobrn/qc71_laptop#8]
sudo insmod qc71_laptop.ko
insmod: ERROR: could not insert module qc71_laptop.ko: File exists

 I get this error. I am not sure what I did wrong. Any help is appreciated it.
I installed using dkms

**Comment by pobrn** [comment]
That means the module is already loaded (you can confirm that by running `lsmod | grep qc71`). If you use `dkms`, you don't need to do anything else, no `insmod`, etc.

**Comment by CuriousxOctopus** [comment]
My bad. I appreciate it friend. Let me know if there is a way I can donate some money for these projects.

**Comment by pobrn** [comment]
This seems to be solved, so I will close it, please reopen it if you still have problems with this.
